# Generated by Django 3.0.1 on 2019-12-22 11:30

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, null=True)),
                ('city', models.CharField(max_length=64, null=True)),
                ('street', models.CharField(max_length=64, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('contact_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('event_status', models.CharField(choices=[('Active event', 'Active event'), ('Stopped event', 'Stopped event'), ('Paused event', 'Paused event')], default='Active event', max_length=64, null=True)),
                ('date', models.DateField()),
                ('facebook', models.CharField(max_length=64, null=True)),
                ('website', models.CharField(max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When event was created', verbose_name='Created at')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('reg_date', models.DateTimeField(auto_now_add=True, help_text='When participant jointed event', verbose_name='Created at')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
            ],
            options={
                'ordering': ['reg_date'],
            },
        ),
    ]
