# Generated by Django 3.0.1 on 2019-12-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='facebook',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='website',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
