# Generated by Django 3.0.1 on 2019-12-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20191223_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('Aktywny', 'Aktywny'), ('Zatrzymany', 'Zatrzymany'), ('Wstrzymany', 'Wstrzymany')], default='Aktywny', max_length=64, null=True),
        ),
    ]
