# Generated by Django 3.0.1 on 2019-12-24 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20191223_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='contact_description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_status',
        ),
        migrations.RemoveField(
            model_name='event',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='event',
            name='street',
        ),
        migrations.RemoveField(
            model_name='event',
            name='website',
        ),
    ]
