# Generated by Django 3.0.1 on 2019-12-24 14:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20191224_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
