# Generated by Django 3.0.1 on 2019-12-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default='18:22'),
            preserve_default=False,
        ),
    ]
