# Generated by Django 3.0.1 on 2019-12-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20191224_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('Aktywny', 'Aktywny'), ('Zatrzymany', 'Zatrzymany'), ('Wstrzymany', 'Wstrzymany')], default='Aktywny', max_length=64, null=True),
        ),
    ]
