# Generated by Django 3.0.1 on 2019-12-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('Aktywne', 'Aktywne'), ('Zatrzymane', 'Zatrzymane'), ('Wstrzymane', 'Wstrzymane')], default='Aktywne', max_length=64, null=True),
        ),
    ]
