# Generated by Django 3.0.1 on 2020-01-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_participants_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
