# Generated by Django 3.0.1 on 2020-01-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20200105_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
