# Generated by Django 3.0.1 on 2020-02-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20200106_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='additional_field',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='if_additional_field',
            field=models.BooleanField(default=False),
        ),
    ]
