# Generated by Django 3.0.1 on 2020-02-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20200213_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='additional_field',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
