# Generated by Django 3.0.1 on 2020-02-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20200213_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='additional_field',
            field=models.BooleanField(default=False),
        ),
    ]
