# Generated by Django 3.0.1 on 2020-02-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_participant_additional_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='if_participants_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='participants_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
