# Generated by Django 3.0.1 on 2020-02-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20200213_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants_limit',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
