# Generated by Django 3.0.3 on 2020-02-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20200214_1311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mailing',
        ),
    ]
