# Generated by Django 3.0.3 on 2020-02-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0003_mailing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('Gotowy', 'Gotowy'), ('Wysyłanie', 'Wysyłanie'), ('Wysłany', 'Wysłany'), ('Błąd', 'Błąd')], default='Gotowy', max_length=64, null=True),
        ),
    ]
