# Generated by Django 3.0.3 on 2020-02-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0005_auto_20200214_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='emails_sent',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
