# Generated by Django 3.0.3 on 2020-02-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailsender', '0007_auto_20200215_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='zipevent_template',
            field=models.BooleanField(default=True),
        ),
    ]
